# Generated by Django 2.2.6 on 2020-07-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastMappingJobs',
            fields=[
                ('data_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=8)),
                ('fasta', models.TextField(null=True)),
                ('result', models.FileField(blank=True, upload_to='')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('processing', models.BooleanField(verbose_name=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
