# Generated by Django 2.2.12 on 2020-09-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastmappingjobs',
            name='map_method',
            field=models.CharField(choices=[('s', 'Closest sequence'), ('st', 'Closest sequence in target species')], default='s', max_length=2),
        ),
    ]
