# Generated by Django 2.2.28 on 2023-06-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastmap', '0003_fastmappingjobs_result_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastmappingjobs',
            name='map_method',
            field=models.CharField(choices=[('s', 'Closest sequence'), ('st', 'Closest sequence in target species'), ('h', 'Closest Hierarchical Orthologous Group (HOG)'), ('ht', 'Closest HOG at a target taxonomic level')], default='h', max_length=2),
        ),
    ]
