# Generated by Django 2.2.28 on 2024-02-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastmap', '0004_auto_20230622_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastmappingjobs',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fastmappingjobs',
            name='runtime',
            field=models.FloatField(default=0),
        ),
    ]
