# Generated by Django 2.2.28 on 2024-02-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastmap', '0005_auto_20240206_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastmappingjobs',
            name='map_method',
            field=models.CharField(choices=[('h', 'Closest Hierarchical Orthologous Group (HOG)'), ('s', 'Closest sequence'), ('st', 'Closest sequence in target species')], default='h', max_length=2),
        ),
    ]
