# Generated by Django 2.2.28 on 2023-06-20 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentAnalysisModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data_hash', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('ancestral', 'Ancestral genome Gene Ontology Enrichment Analysis'), ('extant', 'Extant genome Gene Ontology Enrichment Analysis')], max_length=16)),
                ('_foreground', models.TextField(db_column='foreground', verbose_name='List of genes / hogs that constitute the foreground set.')),
                ('taxlevel', models.CharField(blank=True, max_length=256, verbose_name='Taxonomic level')),
                ('state', models.CharField(max_length=8)),
                ('result', models.FileField(blank=True, upload_to='')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('compute_time', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Name of the enrichment analysis')),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
