# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileResult',
            fields=[
                ('data_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=8)),
                ('result', models.FileField(blank=True, upload_to='')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('purged', models.BooleanField(default=False)),
            ],
        ),
    ]
