# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-14 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileresult',
            name='purged',
        ),
        migrations.AddField(
            model_name='fileresult',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='fileresult',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
