# Generated by Django 5.2.6 on 2026-02-11 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oma", "0003_auto_20230523_0933"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileresult",
            old_name="create_time",
            new_name="created_time",
        ),
        migrations.AddField(
            model_name="fileresult",
            name="access_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fileresult",
            name="last_accessed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fileresult",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fileresult",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fileresult",
            name="runtime_seconds",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="fileresult",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="fileresult",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("error", "Error"),
                    ("timeout", "Timeout"),
                ],
                default="pending",
                max_length=8,
            ),
        ),
    ]
