# Generated by Django 5.2.10 on 2026-02-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oma', '0004_remove_fileresult_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresult',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
