services:
  web:
    restart: ${RESTART_CONTAINERS:-unless-stopped}
    image: $DOCKER_REGISTRY/oma:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: for_docker/oma/Dockerfile
      secrets:
        - labgit
    command: uwsgi --http-socket 0.0.0.0:8000 --master --buffer-size 8192 --processes 3 --module pybrowser_dev.wsgi --vacuum --max-requests=500
    environment:
      - CONTAINER_ROLE=web
      - AUTO_INIT=true
    env_file:
      - env
    volumes:
      # uncomment the following line if you want to use transparently the current checkout mounted
      # into your docker image. convenient for development, but not encouraged in production
      # - ..:/usr/src/pyomabrowser
      - static_volume:${DARWIN_BROWSERSTATIC_PATH}
      - media_volume:${DARWIN_BROWSERMEDIA_PATH}
      - ${RELEASE_PATH_HOST}:${RELEASE_PATH}:ro
    ports:
      - 8000
    depends_on:
      broker:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8000/oma/health/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

  db:
    restart: ${RESTART_CONTAINERS:-unless-stopped}
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    shm_size: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_USER} -d ${SQL_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  broker:
    restart: ${RESTART_CONTAINERS:-unless-stopped}
    image: rabbitmq:3
    env_file:
      - env
    ports:
      - 5672:5672
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
        interval: 5s
        timeout: 5s
        retries: 5

  worker:
    restart: ${RESTART_CONTAINERS:-unless-stopped}
    image: $DOCKER_REGISTRY/oma:${IMAGE_TAG:-latest}
    command: ["celery", "--app=pybrowser_dev.celery_app", "worker", "--concurrency=1",
              "--queues=celery,async_web", "--hostname=worker@%h", "--loglevel=INFO"]
    environment:
      - CONTAINER_ROLE=worker
    env_file:
      - env
    volumes:
      - static_volume:${DARWIN_BROWSERSTATIC_PATH}
      - media_volume:${DARWIN_BROWSERMEDIA_PATH}
      - ${RELEASE_PATH_HOST}:${RELEASE_PATH}:ro
    depends_on:
      - broker
      - db

  worker_long:
    restart: ${RESTART_CONTAINERS:-unless-stopped}
    image: $DOCKER_REGISTRY/oma:${IMAGE_TAG:-latest}
    command: ["celery", "--app=pybrowser_dev.celery_app", "worker", "--concurrency=1",
              "--queues=celery,async_web,long", "--hostname=worker@%h", "--loglevel=INFO"]
    environment:
      - CONTAINER_ROLE=worker
    env_file:
      - env
    volumes:
      - static_volume:${DARWIN_BROWSERSTATIC_PATH}
      - media_volume:${DARWIN_BROWSERMEDIA_PATH}
      - ${RELEASE_PATH_HOST}:${RELEASE_PATH}:ro
      - ${ALLALL_PATH_HOST}:${DARWIN_ALLALL_PATH}:ro
    depends_on:
      - broker
      - db

  nginx:
    restart: ${RESTART_CONTAINERS:-unless-stopped}
    image: $DOCKER_REGISTRY/nginx:${IMAGE_TAG:-latest}
    build:
      context: ./nginx
    ports:
      - ${WEBSERVER_PORT:-80}:80
    volumes:
      - static_volume:${DARWIN_BROWSERSTATIC_PATH}
      - media_volume:${DARWIN_BROWSERMEDIA_PATH}
      - ${RELEASE_PATH_HOST}/downloads:${DARWIN_BROWSERDOWNLOAD_PATH}:ro
      - ${NGINX_SNIPPET_PATH_HOST:-/dev/null}:${NGINX_SNIPPET_PATH:-/etc/nginx/snippets}
      - ${NGINX_LOG_PATH_HOST:-/dev/null}:/var/log/nginx
    environment:
      - DEPLOYMENT_TYPE=${DEPLOYMENT_TYPE}
      - DARWIN_BROWSERSTATIC_PATH=${DARWIN_BROWSERSTATIC_PATH}
      - DARWIN_BROWSERMEDIA_PATH=${DARWIN_BROWSERMEDIA_PATH}
      - DARWIN_BROWSERDOWNLOAD_PATH=${DARWIN_BROWSERDOWNLOAD_PATH}
      - NGINX_SNIPPET_PATH=${NGINX_SNIPPET_PATH:-/etc/nginx/snippets}
      - NGINX_LOG_TO_FILE=${NGINX_LOG_TO_FILE:-false}
      - REVERSE_PROXY_IP=${REVERSE_PROXY_IP:-}
      # USER_AGENT_BOT_FILE and SUBNET_BOT_FILE are relative to NGINX_SNIPPET_PATH_HOST
      # they can be used to block known crawlers/crawlers coming from known subnets
      # an example of both files is provided in ./nginx/snippets/*.conf.template
      - USER_AGENT_BOT_FILE=${USER_AGENT_BOT_FILE:-}
      - SUBNET_BOT_FILE=${SUBNET_BOT_FILE:-}
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  # if release data is used with a docker volume, uncomment release_volume line and
  # set RELEASE_PATH_HOST="release_volume" in env file
  #release_volume:


secrets:
  labgit:
    file: "./labgit.cnf"
