# Generated by Django 2.2.28 on 2024-02-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standaloneexportjobs',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
