# Generated by Django 5.2.15 on 2026-06-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("zenodo_record_id", models.CharField(blank=True, max_length=50)),
                ("zenodo_doi", models.CharField(blank=True, max_length=100)),
                (
                    "release_group",
                    models.CharField(db_index=True, default="All", max_length=50),
                ),
                ("is_latest", models.BooleanField(db_index=True, default=False)),
                ("release_date", models.DateField()),
            ],
            options={
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="ZenodoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("zenodo_url", models.URLField(max_length=500)),
                ("size", models.BigIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, max_length=100)),
                ("source_record_id", models.CharField(blank=True, max_length=50)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="downloads.release",
                    ),
                ),
            ],
            options={
                "unique_together": {("release", "filename")},
            },
        ),
        migrations.CreateModel(
            name="DownloadEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_events",
                        to="downloads.zenodofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["file", "timestamp"],
                        name="downloads_d_file_id_b58a4a_idx",
                    )
                ],
            },
        ),
    ]
